### PR TITLE
Cd wars ends with

### PR DESCRIPTION
**Pull request by TreverArnold**

### CODE REVIEW

**Review by W-Ely — APPROVED** [review]
Great. Moving forward I expect not to see the hello word files in these PRs because you are supposed to pull main before you create each branch.

**Comment by W-Ely** [comment]
Every branch should come from main:

These commits say other wise. 
Screen Shot 2023-09-04 at 9 32 10 AM

**Comment by W-Ely** [comment]
Git Flow!

**Comment by TreverArnold** [comment]
My bad on that , ive been forgetting to pull each time.

**Pull request merged**
